- name: Provision a GeoNode into Production
  hosts: production
  remote_user: ubuntu
  vars:
    app_name: worldmap
    github_user: geonode
    server_name: 0.0.0.0
    deploy_user: ubuntu
    code_repository: https://github.com/-----/worldmap.git" # e.g., "https://github.com/GeoNode/worldmap.git"
    branch_name: master
    virtualenv_dir: "/home/ubuntu/.venvs"
    site_url: "http://localhost:8000/" # The public url of the GeoNode instance
    geoserver_url: "http://build.geonode.org/geoserver/latest/geoserver-2.13.x.war" # geoserver_url should match what is found in dev_config.yml
    pg_max_connections: 100
    pg_shared_buffers: 128MB
    tomcat_xms: "1024M"
    tomcat_xmx: "2048M"
    nginx_client_max_body_size: "400M"
    letsencrypt: False
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      become: yes
      become_user: root
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - name: 'Reconfigue Locales'
      become: yes
      become_user: root
      shell: ""
      with_items:
        - "export LANGUAGE=en_US.UTF-8"
        - "export LANG=en_US.UTF-8"
        - "export LC_ALL=en_US.UTF-8"
        - "locale-gen --purge en_US.UTF-8"
        - "echo 'LANG=en_US.UTF-8\nLANGUAGE=en_US:en\n' > /etc/default/locale"
    - name: "Install cul, vim, and unzip"
      become: yes
      become_user: root
      apt: name="" state=latest
      with_items:
        - curl
        - vim
        - unzip
    - setup: # aka gather_facts
  roles:
     - { role: GeoNode.geonode }
